name: "GitHub Action for red* OCaml packages"
description: "Workflow shared by all red* OCaml packages for building, testing, and documentation updates"
branding:
  icon: "box"
  color: "red"
inputs:
  ocaml-compiler:
    description: "OCaml Compiler Version"
    required: true
  with-doc:
    description: "Whether to build package documentation"
    required: false
    default: false
  publish-doc-if-built:
    description: "Whether to publish package documentation"
    required: false
    default: true
  cache-prefix:
    description: "The cache-prefix passed to the setup-ocaml action"
    required: false
    default: "v1"
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: "Detect OCaml 5"
      shell: sh
      run: |
        echo "IS_OCAML_5=${{ startsWith(inputs.ocaml-compiler, 'ocaml-variants.5') || startsWith(inputs.ocaml-compiler, 'ocaml-base-compiler.5') || startsWith(inputs.ocaml-compiler, '5') }}" >> $GITHUB_ENV
    - name: "Set up OCaml"
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ inputs.ocaml-compiler }}
        cache-prefix: ${{ inputs.cache-prefix }}
        opam-repositories: |
          default: https://opam.ocaml.org
          # HACK: When we read the IS_OCAML_5 environment variable, it gets interpreted as a string,
          # not a boolean. Therefore, we have to do an equality check against the string 'true' here.
          ${{ env.IS_OCAML_5 == 'true' && 'alpha: git+https://github.com/kit-ty-kate/opam-alpha-repository.git' || '' }}
    - name: "Install the dependencies"
      shell: sh
      run: opam install --with-test ${{inputs.with-doc == 'true' && '--with-doc' || ''}} --deps-only --yes --verbose .
    - name: "Build the package"
      shell: sh
      run: opam exec -- dune build
    - name: "Test the package"
      shell: sh
      run: opam exec -- dune runtest
    - name: "Build the documentation"
      if: ${{ inputs.with-doc == 'true' }}
      shell: sh
      run: opam exec -- dune build @doc
    - name: "Publish the documentation"
      if: ${{ inputs.with-doc == 'true' && inputs.publish-doc-if-built == 'true' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: "./_build/default/_doc/_html/"
